Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Registration.Models;
using Registration.Data;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

namespace Registration.Controllers
{
    public class CourseController : Controller
    {
        private readonly RegistrationContext _context;

        public CourseController(RegistrationContext context)
        {
            _context = context;
        }

        // GET: Course
        public async Task<IActionResult> Index()
        {
            var courses = await _context.Course.Include(course => course.Department).ToListAsync();

            courses = courses.OrderBy(c => c.FullCourseNumber()).ToList();

            return View(courses);
        }

        // GET: Course/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .Include(c => c.Department)
                .FirstOrDefaultAsync(m => m.CourseId == id);

            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // GET: Course/Create
        [Authorize(Policy = "Staff")]
        public IActionResult Create()
        {
            var courseViewModel = new CourseViewModel()
            {
                Departments = DepartmentsToSelectListItems()
            };

            return View(courseViewModel);
        }

        // POST: Course/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Policy = "Staff")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Course course)
        {
            if (course.DepartmentId != 0)
            {
                var department = _context.Department.Find(course.DepartmentId);
                
                if (department != null)
                {
                    course.Department = department;
                    course.Students = new List<Student>();
                    ModelState.ClearValidationState(nameof(course));
                    TryValidateModel(course, nameof(course));
                }
            }

            if (ModelState.IsValid)
            {
                _context.Add(course);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            var courseViewModel = new CourseViewModel()
            {
                Course = course,
                Departments = DepartmentsToSelectListItems()
            };
            
            return View(courseViewModel);
        }

        // GET: Course/Edit/5
        [Authorize(Policy = "Staff")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course.FindAsync(id);

            _context.Entry(course)
                .Reference(c => c.Department)
                .Load();

            if (course == null)
            {
                return NotFound();
            }
            var courseViewModel = new CourseViewModel()
            {
                Course = course,
                Departments = DepartmentsToSelectListItems()
            };

            return View(courseViewModel);
        }

        // POST: Course/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Policy = "Staff")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Course course)
        {
            if (id != course.CourseId)
            {
                return NotFound();
            }

            var currentCourse = await _context.Course.FindAsync(id);

            if (currentCourse == null)
            {
                return NotFound();
            }
            else
            {
                _context.Entry(currentCourse).Collection(c => c.Students).Load();
                course.Students = currentCourse.Students;
            }

            if (course.DepartmentId != 0)
            {
                var department = _context.Department.Find(course.DepartmentId);

                if (department != null)
                {
                    course.Department = department;
                    ModelState.ClearValidationState(nameof(course));
                    TryValidateModel(course, nameof(course));
                }
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Entry(currentCourse).CurrentValues.SetValues(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.CourseId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            var courseViewModel = new CourseViewModel()
            {
                Course = course,
                Departments = DepartmentsToSelectListItems()
            };

            return View(courseViewModel);
        }

        // GET: Course/Delete/5
        [Authorize(Policy = "Staff")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .Include(c => c.Department)
                .FirstOrDefaultAsync(m => m.CourseId == id);

            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: Course/Delete/5
        [Authorize(Policy = "Staff")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _context.Course.FindAsync(id);
            _context.Course.Remove(course);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
            return _context.Course.Any(e => e.CourseId == id);
        }

        private List<SelectListItem> DepartmentsToSelectListItems()
        {
            var departments = _context.Department.ToList();

            return departments.Select(x => new SelectListItem(x.Name, x.DepartmentId.ToString())).ToList();
        }
    }
}

Controllers/ReportController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Registration.Data;

namespace Registration.Controllers
{
    public class ReportController : Controller
    {
        private readonly RegistrationContext _context;

        public ReportController(RegistrationContext context)
        {
            _context = context;
        }

        [Authorize(Policy = "Staff")]
        public async Task<IActionResult> Index()
        {
            var courses = await _context.Course
                .Include(c => c.Department)
                .Include(c => c.Students)
                .ToListAsync();

            courses = courses.OrderBy(c => c.FullCourseNumber()).ToList();
            
            return View(courses);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-theme="light">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>University Registration System - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/output.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Registration.styles.css" asp-append-version="true" />
</head>
<body>
    <header class="container mx-auto mt-4">
        @await Html.PartialAsync("~/Views/Shared/_Navbar.cshtml")
    </header>

    <div class="container mx-auto">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="container mx-auto">
        <div class="p-4 footer bg-neutral text-neutral-content footer-center rounded-box">
            <p>ITEC 6410 - Fall 2021</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Navbar.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService

<div class="navbar mb-2 shadow-lg bg-neutral text-neutral-content rounded-box">
    <div class="flex-none px-2 mx-2">
        <span class="text-lg font-bold">
            University Registration System
        </span>
    </div> 
    <div class="flex-1 px-2 mx-2">
        <div class="items-stretch hidden lg:flex">
            <a asp-controller="Course" asp-action="Index" class="btn btn-ghost btn-sm rounded-btn">Courses</a>
        </div>
        @if ((await AuthorizationService.AuthorizeAsync(User, "Staff")).Succeeded)
        {
            <div class="items-stretch hidden lg:flex">
                <a asp-controller="Report" asp-action="Index" class="btn btn-ghost btn-sm rounded-btn">Report</a>
            </div>
        }
        @if ((await AuthorizationService.AuthorizeAsync(User, "Student")).Succeeded)
        {
            <div class="items-stretch hidden lg:flex">
                <a asp-controller="Schedule" asp-action="Index" class="btn btn-ghost btn-sm rounded-btn">Schedule</a>
            </div>
        }
    </div>
    @if (User.Identity.IsAuthenticated)
    {
        <div class="flex-1 flex-none">
            <div class="form-control">
                @User.Identity.Name
            </div>
        </div>
        <div class="flex-none">
            <div class="form-control ml-4">
                <a asp-action="Logout" asp-controller="Account" class="btn btn-ghost">Logout</a>
            </div>
        </div>
    } else
    {
        <form asp-action="Login" asp-controller="Account">
            <div class="flex-1 flex-none">
                <div class="form-control">
                    <input type="text" name="username" placeholder="Username" class="input input-ghost">
                </div>
            </div>
            <div class="flex-none">
                <div class="form-control ml-4">
                    <input type="password" name="password" placeholder="Password" class="input input-ghost">
                </div>
            </div>
            <div class="flex-none">
                <div class="form-control ml-4">
                    <input type="submit" value="Login" class="btn btn-ghost" />
                </div>
            </div>
        </form>
    }
</div>